version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: leitor-de-laudos-back-user
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-user-cliee
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha-rede

  backend:
    build:
      context: .
    container_name: leitor-de-laudos-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db-user-cliee
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - minha-rede

volumes:
  postgres_data:

networks:
  minha-rede:
